version: "3.1"

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: secretary
      POSTGRES_DB: secretary
      POSTGRES_USER: secretary
    ports:
      - "5432:5432"

  secretary:
    image: registry.gitlab.com/bettersolutions/reksio/secretary:latest
    depends_on:
      - postgres
    volumes:
      - ./config/secretary/application.properties:/config/application.properties
    links:
      - "postgres:postgres"
    ports:
      - "8080:8080"

  rtsp-client:
    image: registry.gitlab.com/bettersolutions/reksio/rtsp-client:latest
    depends_on:
      - secretary
    environment:
      RTSP_IP: 192.168.88.10
      RTSP_PORT: 8554
      RTSP_RESOURCE_NAME: test
      SECRETARY_URL: secretary:8080/
      VIDEO_DURATION: 30

  minio1:
    image: minio/minio:RELEASE.2019-10-12T01-39-57Z
    volumes:
      - data1-1:/data1
      - data1-2:/data2
    ports:
      - "9001:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server http://minio{1...4}/data{1...2}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  minio2:
    image: minio/minio:RELEASE.2019-10-12T01-39-57Z
    volumes:
      - data2-1:/data1
      - data2-2:/data2
    ports:
      - "9002:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server http://minio{1...4}/data{1...2}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  minio3:
    image: minio/minio:RELEASE.2019-10-12T01-39-57Z
    volumes:
      - data3-1:/data1
      - data3-2:/data2
    ports:
      - "9003:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server http://minio{1...4}/data{1...2}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  minio4:
    image: minio/minio:RELEASE.2019-10-12T01-39-57Z
    volumes:
      - data4-1:/data1
      - data4-2:/data2
    ports:
      - "9004:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server http://minio{1...4}/data{1...2}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

## By default this config uses default local driver,
## For custom volumes replace with volume driver configuration.
volumes:
  data1-1:
  data1-2:
  data2-1:
  data2-2:
  data3-1:
  data3-2:
  data4-1:
  data4-2:
